RinconFeliz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.administracion.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/administracion/alumno_tutor/urls.py
from django.views.generic.base import TemplateView
from django.urls import path
from .views import *

urlpatterns = [
    path('registro-tutor/', CrearTutor.as_view(), name='crear_tutor'),
    path('tutores/', ListarTutores.as_view(), name='lista_tutores'),
    path('editar-tutor/<pk>/', ModificarTutor.as_view(), name='editar_tutor'),
    path('registro-alumno/', CrearAlumno.as_view(), name='crear_alumno'),
    path('alumno/<pk>/', DetalleAlumno.as_view(), name='detalle_alumno'),
    path('alumnos/', ListarAlumnos.as_view(), name='lista_alumnos'),
    path('editar-alumno/<pk>/',
         ModificarAlumno.as_view(),
         name='editar_alumno'),
    path('asistencias/', ListarAsistencias.as_view(),
         name='lista_asistencias'),
    path('registro-asistencia/',
         CrearAsistencia.as_view(),
         name='crear_asistencia'),
    path('editar-asistencia/<pk>/',
         ModificarAsistencia.as_view(),
         name='editar_asistencia'),
]

apps/administracion/gastos/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('registro-proveedor/',
         CrearProveedor.as_view(),
         name='crear_proveedor'),
    path('proveedores/', ListarProveedor.as_view(), name='lista_proveedores'),
    path('editar-proveedor/<pk>/', ModificarProveedor.as_view(), name='editar_proveedor'),
    path('registro-compra/', CrearCompra.as_view(), name='crear_compra'),
    path('compras/', ListarCompra.as_view(), name='lista_compras'),
    path('editar-compra/<pk>/',
         ModificarCompra.as_view(),
         name='editar_compra'),
]

apps/administracion/personal/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('empleados/', ListarPersonal.as_view(), name='lista_personal'),
    path('editar-empleado/<pk>/',
         ModificarPersonal.as_view(),
         name='editar_personal'),
    path('registro-personal/', CrearPersonal.as_view(), name='crear_personal'),
]

apps/administracion/urls.py
from django.urls import path
from django.urls.conf import include
from .views import *

app_name = 'administracion'

urlpatterns = [
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('alumno-tutor/', include('apps.administracion.alumno_tutor.urls')),
    path('gastos/', include('apps.administracion.gastos.urls')),
    path('personal/', include('apps.administracion.personal.urls')),
    path('talleres-actividades/',
         include('apps.administracion.talleres_actividades.urls')),
]

templates/base_back.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {# CSS Files #}
    <link rel="stylesheet" href="{% static 'css/clases.css' %}">
    <link rel="stylesheet" href="{% static 'css/base_back.css' %}">
    <link rel="stylesheet" href="{% static 'lib/JQuery-Confirm-v3.3.4/css/jquery-confirm.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton">
    {# Script Files #}
    <script src="https://kit.fontawesome.com/90e0fff1f3.js" crossorigin="anonymous"></script>
    <script src="{% static 'lib/JQuery/jquery.min.js' %}"></script>
    <script src="{% static 'lib/JQuery-Confirm-v3.3.4/js/jquery-confirm.min.js' %}"></script>
    {% block head %}{% endblock %}
</head>

<body class="body">
    <div class="burgger__div">Menu</div>
    <input class="burgger" type="checkbox">
    <aside class="aside">
        <div class="aside__container">
            <a href="{% url 'administracion:dashboard' %}">
                <div class="aside__div">
                    <img src="{% static 'img/EPI_Rincon_Feliz.jpg' %}" title="Rincón Feliz">
                </div>
            </a>
            <div class="aside__div">
                <img src="{% static 'img/alumnos.svg' %}" title="Alumnos y Tutores">
                <a href="{% url 'administracion:lista_tutores' %}">Tutores</a>
                <a href="{% url 'administracion:lista_alumnos' %}">Alumnos</a>
            </div>
            <div class="aside__div">
                <img src="{% static 'img/personal.svg' %}" title="Personal">
                <a href="{% url 'administracion:lista_personal' %}">Personal</a>
                {# <a href="{% url 'administracion:crear_personal' %}">Registro Personal</a> #}
            </div>
            <div class="aside__div">
                <img src="{% static 'img/gastos.svg' %}" title="Gastos">
                <a href="{% url 'administracion:lista_proveedores' %}">Proveedores</a>
                <a href="{% url 'administracion:lista_compras' %}">Compras</a>
            </div>
            <div class="aside__div">
                <img src="{% static 'img/select.svg' %}" title="Talleres y Actividades">
            </div>
        </div>
    </aside>
    <section class="section">
        {% block content %}{% endblock %}
    </section>
    
    {% block javascript %} {% endblock %}
</body>

</html>

templates/dashboard.html
{% extends 'base_back.html' %}

{% block title %}Dashboard{% endblock %}

templates/listar.html
{% extends 'base_back.html' %}
{% load static %}

{% block title %} {{ title }} {% endblock %}

{% block head %}
{# CSS Files #}
<link rel="stylesheet" href="{% static 'css/listar.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'lib/DataTables/datatables.min.css' %}" />
<link rel="stylesheet" href="{% static 'lib/DataTables/Responsive-2.2.7/css/responsive.dataTables.min.css' %}" />
<link rel="stylesheet" href="{% static 'lib/DataTables/Buttons-1.7.0/css/buttons.dataTables.min.css' %}">

{# JS Files #}
<script src="{% static 'lib/DataTables/datatables.min.js' %}"></script>
<script src="{% static 'lib/DataTables/Responsive-2.2.7/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'lib/DataTables/Buttons-1.7.0/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'lib/DataTables/Buttons-1.7.0/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'lib/DataTables/Buttons-1.7.0/js/pdfmake.min.js' %}"></script>
<script src="{% static 'lib/DataTables/Buttons-1.7.0/js/jszip.min.js' %}"></script>
<script src="{% static 'lib/DataTables/Buttons-1.7.0/js/vfs_fonts.js' %}"></script>
{% endblock %}

{% block content %}
<div class="table__container">
    <h2 class="fix-title">{{ title | safe }}</h2>

    
    {# Button Nuevo Registro #}
    {% if title == 'Alumnos' %}
    <a href="{% url 'administracion:crear_alumno' %}" class="btn btn-outline-dark registrar">Registrar {{title}}</a>
    {% elif title == 'Asistencias' %}
    <a href="{% url 'administracion:crear_asistencia' %}" class="btn btn-outline-dark registrar">Registrar {{title}}</a>
    {% elif title == 'Tutores' %}
    <a href="{% url 'administracion:crear_tutor' %}" class="btn btn-outline-dark registrar">Registrar {{title}}</a>
    {% elif title == 'Proveedores' %}
    <a href="{% url 'administracion:crear_proveedor' %}" class="btn btn-outline-dark registrar">Registrar {{title}}</a>
    {% elif title == 'Compras' %}
    <a href="{% url 'administracion:crear_compra' %}" class="btn btn-outline-dark registrar">Registrar {{title}}</a>
    {% else %}
    <a href="{% url 'administracion:crear_personal' %}" class="btn btn-outline-dark registrar">Registrar {{title}}</a>
    {% endif %}
    
    {% block extra_content %} {% endblock %}
    
    <table id="table_id" class="cell-border">
        <thead>
            {% block thead %} {% endblock %}
        </thead>
        <tbody id="tBody">
            {% block tbody %} {% endblock %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/administracion/listar.js' %}"></script>
{% block extraScript %}{% endblock %}
{% endblock %}

templates/registrar.html
{% extends 'base_back.html' %}
{% load static %}

{% block title %} {{ title }} {% endblock %}

{% block head %}
{# Forms CSS File #}
<link rel="stylesheet" href="{% static 'css/clases.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
<h2 class="fix-title">{{title}}</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{ msj }} </p>
    <div class="form">
        {% for field in form %}
        <div class="form-field">
            <label>{{ field.label }}:</label>
            {% if title == 'Nuevo Alumno' and forloop.counter == 7 %}
            <div>
                {{ field }}
                <a href="{% url 'administracion:crear_tutor' %}" title="Añadir Tutor">
                    <i class="fas fa-plus-circle"></i>
                </a>
            </div>
            {% elif title == 'Nueva Compra' and forloop.counter == 2 %}
            <div>
                {{ field }}
                <a href="{% url 'administracion:crear_proveedor' %}" title="Añadir Proveedor">
                    <i class="fas fa-plus-circle"></i>
                </a>
            </div>
            {% else %}
            {{ field }}
            {% endif %}


            {% if field.errors %}
            {{ field.errors }}
            {% endif %}

        </div>
        {% endfor %}
    </div>
    <input type="submit" value="Registrar" class="btn btn-outline-success">
</form>
{% endblock %}